
DROP TABLE IF EXISTS photo_attactment;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS blog;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;




create table blog
(
    id          bigint generated by default as identity,
    create_at   varchar(255),
    create_by   varchar(255),
    description varchar(255),
    title varchar(255),
    primary key (id)
);

create table comment
(
    id        uuid default random_uuid() not null,
    body      varchar(255),
    create_at varchar(255),
    create_by varchar(255),
    blog_id   bigint,
    primary key (id),
    foreign key (blog_id)
        references blog
);

create table photo_attactment
(
    id           uuid default random_uuid() not null,
    blog_id      bigint,
    content      blob,
    content_type varchar(255),
    filename     varchar(255),
    primary key (id),
    foreign key (blog_id)
        references blog
);


create table users
(
    username varchar(255) not null,
    password varchar(255),
    phone varchar(255),
    email varchar(255),
    description varchar(255),
    primary key (username)
);

create table user_roles
(
    user_role_id integer generated by default as identity,
    role         varchar(255),
    username     varchar(255),
    primary key (user_role_id),
    foreign key (username)
        references users
);









